### ISSUE TITLE
I2S on Dodepan

### ISSUE THREAD

**Issue by grbfst** [TuriSc/Dodepan#1]
Hi,
Love the project. How hard/easy is it to implement an I2S sound output on the Dodepan? I see you have already done it for the Picophonica so maybe it's easy (and I don't know how) ?

**Comment by TuriSc** [comment]
Hi.
A new version of Dodepan is under development at [TuriSc/Dodepan-I2S](https://github.com/TuriSc/Dodepan-I2S/). It does output sound via I2S, but it's not sample-based as it uses a new audio engine for direct digital synthesis.
This older repository will only cover the PWM version of the instrument.
