### ISSUE TITLE
Crackling

### ISSUE THREAD

**Issue by grbfst** [TuriSc/Dodepan#2]
Hi, Wonderful project! Just built a Pico (1) and a Pico 2 Dodepan. I noticed quite some crackling, do I need to change something in the I2S settings?

Regards,
Marc

**Comment by TuriSc** [comment]
What type of crackling do you hear? Is it there all the time or only when a note is being played?
I would try disconnecting R1 and reconnecting GAIN_SLOT to VDD via the 100KΩ resistor. This will lower the gain considerably.
You can also leave the resistor unconnected for the default gain setting.

**Comment by grbfst** [comment]
It's only when playing a note, I do need the gain because without the resistor the sound is quite soft. I tried no resistor, resistor to ground and to VDD but all give crackling. 
I just noticed it happens when playing more than one note simultaneously. Single notes play fine.

**Comment by TuriSc** [comment]
Could you please try a smaller speaker (or headphones)? If the crackling stops or is reduced, then it's a power issue, and a decoupling capacitor between the amp's VDD and GND might help.

However, it could be that your CPU is struggling to keep up with audio buffering. Does the problem go away if you disable the two IMU-controlled effects? Disabling them frees up quite some CPU cycles.

A Pico 1 would not be fast enough to flawlessly play multiple notes and process IMU effects at the same time, unless the CPU is overclocked even more, which will affect the overall tuning of the instrument.

**Comment by grbfst** [comment]
I will look at the code and see if where I can disable the effects.
